# Site settings
title: tsureshkumar.github.io
email: tsureshkumar2000@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tsureshkumar.github.com" # the base hostname & protocol for your site
twitter_username: tsureshkumar
github_username:  tsureshkumar

# Build settings
markdown: kramdown

# collections
collections:
    - projects
